In [1]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

## **Dataset Load**

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [3]:
df.shape

(569, 33)

In [4]:
df.drop(columns=['id', 'Unnamed: 32'], inplace=True)

In [5]:
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

## **Train Test Split**

In [6]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

## **Scaling**

In [7]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [8]:
X_train

array([[-0.75187324, -0.74515838, -0.77882348, ..., -0.73960245,
        -0.05448262,  0.20654982],
       [-0.59997953,  1.27652385, -0.58380526, ...,  0.10725668,
        -0.47751889, -0.07379676],
       [-0.49774338,  1.72604011, -0.43339905, ...,  0.50499571,
         0.55656978,  2.00635293],
       ...,
       [-0.71389982, -1.47305526, -0.72273981, ..., -0.44539938,
        -0.18710113,  0.20271695],
       [ 0.05141082,  0.87264377,  0.12828743, ...,  0.98940161,
         3.83174349,  3.32595302],
       [ 1.12927199,  0.39346401,  1.40419098, ...,  1.28654517,
         0.60693124,  1.96802429]])

In [9]:
y_train

348    B
445    B
193    M
130    B
396    B
      ..
219    M
416    B
98     B
190    M
400    M
Name: diagnosis, Length: 455, dtype: object

## **Label Encoding**

In [10]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [11]:
y_train

array([0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1,
       0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1,
       0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1,
       1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0,
       0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0,
       1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1,
       1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0,

## **Numpy arrays to PyTorch Tensors**

In [29]:
X_train_tensor = torch.from_numpy(X_train.astype(np.float32))
X_test_tensor = torch.from_numpy(X_test.astype(np.float32))
y_train_tensor = torch.from_numpy(y_train.astype(np.float32))
y_test_tensor = torch.from_numpy(y_test.astype(np.float32))

In [30]:
X_train_tensor.shape

torch.Size([455, 30])

In [31]:
y_train_tensor.shape

torch.Size([455])

## **Defining the model**

In [45]:
import torch.nn as nn

class SimpleNN(nn.Module):
  def __init__(self, num_features):
    super().__init__()
    self.linear = nn.Linear(num_features, 1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):
    out = self.linear(features)
    out = self.sigmoid(out)
    return out

  # def loss_func(self, y_pred, y):
  #   epsilon = 1e-7 #Clamp prediction to avoid log(0)
  #   y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)

  #   loss = -(y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor) * torch.log(1 - y_pred)).mean() #Calculate loss
  #   return loss

In [46]:
learning_rate = 0.1
epochs = 25

In [47]:
# define loss function
loss_function = nn.BCELoss()

## **Training Pipeline**

In [48]:
#model
model = SimpleNN(X_train_tensor.shape[1])

# #Optimizer
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

#Loop
for epoch in range(epochs):

  #Forward pass
  y_pred = model(X_train_tensor)

  #loss Calculate
  loss = loss_function(y_pred, y_train_tensor.view(-1,1))

  # #clear gradients
  optimizer.zero_grad()

  #backward pass
  loss.backward()

  #Parameter update
  optimizer.step()

  # #Parameter update
  # with torch.no_grad():
  #   model.linear.weight -= learning_rate * model.linear.weight.grad
  #   model.linear.bias -= learning_rate * model.linear.bias.grad

  # #zero gradients
  # model.linear.weight.grad.zero_()
  # model.linear.bias.grad.zero_()

  #print loss in each epochs
  print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')

Epoch: 1, Loss: 0.6669952273368835
Epoch: 2, Loss: 0.5145690441131592
Epoch: 3, Loss: 0.4302387535572052
Epoch: 4, Loss: 0.37784329056739807
Epoch: 5, Loss: 0.3415866792201996
Epoch: 6, Loss: 0.3145921230316162
Epoch: 7, Loss: 0.29347047209739685
Epoch: 8, Loss: 0.27635279297828674
Epoch: 9, Loss: 0.2621135115623474
Epoch: 10, Loss: 0.25002768635749817
Epoch: 11, Loss: 0.23960383236408234
Epoch: 12, Loss: 0.23049494624137878
Epoch: 13, Loss: 0.22244784235954285
Epoch: 14, Loss: 0.21527284383773804
Epoch: 15, Loss: 0.20882456004619598
Epoch: 16, Loss: 0.2029893696308136
Epoch: 17, Loss: 0.19767703115940094
Epoch: 18, Loss: 0.19281479716300964
Epoch: 19, Loss: 0.188343346118927
Epoch: 20, Loss: 0.18421360850334167
Epoch: 21, Loss: 0.18038475513458252
Epoch: 22, Loss: 0.17682240903377533
Epoch: 23, Loss: 0.17349743843078613
Epoch: 24, Loss: 0.1703849583864212
Epoch: 25, Loss: 0.167463481426239


In [49]:
model.linear.weight

Parameter containing:
tensor([[ 0.2789,  0.0631,  0.4056,  0.4113,  0.2109,  0.0668,  0.0285,  0.3923,
          0.0594,  0.0072,  0.0594,  0.1014,  0.0461,  0.0738,  0.0933,  0.1111,
         -0.1226,  0.0550, -0.1193, -0.1235,  0.1042,  0.3434,  0.2126,  0.4285,
          0.2116,  0.2678,  0.2100,  0.1325,  0.2377,  0.0144]],
       requires_grad=True)

In [50]:
model.linear.bias

Parameter containing:
tensor([-0.1571], requires_grad=True)

## **Evaluation**

In [51]:
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred = (y_pred > 0.5).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy}')


Accuracy: 0.5180055499076843
