In [1]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

## **Dataset Load**

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [3]:
df.shape

(569, 33)

In [4]:
df.drop(columns=['id', 'Unnamed: 32'], inplace=True)

In [5]:
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

## **Train Test Split**

In [6]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

## **Scaling**

In [7]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [8]:
X_train

array([[ 1.14242613, -0.09165378,  1.0851519 , ...,  0.96587283,
        -0.13047453, -0.08903873],
       [-0.59196345, -1.3623856 , -0.5894709 , ..., -0.60641241,
        -0.18034158, -0.1683283 ],
       [-0.15484087,  0.92867601, -0.20595073, ..., -0.6396265 ,
        -0.40393898, -0.76517238],
       ...,
       [-1.24482717,  2.09175835, -1.25120709, ..., -0.98966358,
        -0.92030419, -0.62505793],
       [ 1.90386546,  1.36395431,  2.08082927, ...,  2.12760765,
         0.05773335,  0.82061897],
       [-0.6258052 , -1.0066743 , -0.61405553, ..., -1.00482983,
         0.37141315, -0.41923091]])

In [9]:
y_train

317    M
529    B
545    B
346    B
229    M
      ..
477    B
522    B
459    B
563    M
349    B
Name: diagnosis, Length: 455, dtype: object

## **Label Encoding**

In [10]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [11]:
y_train

array([1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0,
       1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1,
       0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1,
       1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1,
       1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0,

## **Numpy arrays to PyTorch Tensors**

In [12]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [13]:
X_train_tensor.shape

torch.Size([455, 30])

In [14]:
y_train_tensor.shape

torch.Size([455])

## **Defining the model**

In [15]:
class SimpleNN():
  def __init__(self, X):
    self.weights = torch.rand((X.shape[1], 1), dtype=torch.float64, requires_grad=True)
    self.bias = torch.zeros(1, dtype=torch.float64, requires_grad=True)

  def forward(self, X):
    z = torch.matmul(X, self.weights) + self.bias
    y_pred = torch.sigmoid(z)
    return y_pred

  def loss_func(self, y_pred, y):
    epsilon = 1e-7 #Clamp prediction to avoid log(0)
    y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)

    loss = -(y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor) * torch.log(1 - y_pred)).mean() #Calculate loss
    return loss

In [16]:
learning_rate = 0.1
epochs = 25

## **Training Pipeline**

In [17]:
#model
model = SimpleNN(X_train_tensor)

#Loop
for epoch in range(epochs):

  #Forward pass
  y_pred = model.forward(X_train_tensor)

  #loss Calculate
  loss = model.loss_func(y_pred, y_train_tensor)

  #backward pass
  loss.backward()

  #Parameter update
  with torch.no_grad():
    model.weights.data -= learning_rate * model.weights.grad
    model.bias.data -= learning_rate * model.bias.grad

  #zero gradients
  model.weights.grad.zero_()
  model.bias.grad.zero_()

  #print loss in each epochs
  print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')

Epoch: 1, Loss: 3.768181707428653
Epoch: 2, Loss: 3.6422188126043626
Epoch: 3, Loss: 3.5120694322748505
Epoch: 4, Loss: 3.3780548917636
Epoch: 5, Loss: 3.244548284663903
Epoch: 6, Loss: 3.1086137759322314
Epoch: 7, Loss: 2.9659813645181186
Epoch: 8, Loss: 2.8171560397897504
Epoch: 9, Loss: 2.664412088309516
Epoch: 10, Loss: 2.5097272925465206
Epoch: 11, Loss: 2.3456334973826105
Epoch: 12, Loss: 2.1838054768712647
Epoch: 13, Loss: 2.024116943145789
Epoch: 14, Loss: 1.8621484368984569
Epoch: 15, Loss: 1.7040794727014013
Epoch: 16, Loss: 1.5497547174545823
Epoch: 17, Loss: 1.408136507749563
Epoch: 18, Loss: 1.2809613669378412
Epoch: 19, Loss: 1.1698377535550795
Epoch: 20, Loss: 1.0759976980184944
Epoch: 21, Loss: 0.999936186923729
Epoch: 22, Loss: 0.9409404456017961
Epoch: 23, Loss: 0.8966672390135684
Epoch: 24, Loss: 0.8637176293403427
Epoch: 25, Loss: 0.8388943996428908


In [18]:
model.weights

tensor([[-0.0719],
        [ 0.0833],
        [ 0.1726],
        [-0.1967],
        [ 0.3232],
        [-0.1594],
        [-0.3737],
        [-0.3209],
        [ 0.1507],
        [ 0.0617],
        [-0.0961],
        [ 0.6028],
        [ 0.0885],
        [-0.3273],
        [ 0.2364],
        [ 0.3146],
        [-0.0740],
        [-0.2330],
        [ 0.2352],
        [-0.1493],
        [ 0.1559],
        [ 0.3959],
        [ 0.0728],
        [ 0.3698],
        [-0.2350],
        [ 0.3487],
        [ 0.1331],
        [ 0.2533],
        [ 0.3018],
        [-0.2188]], dtype=torch.float64, requires_grad=True)

In [19]:
model.bias

tensor([-0.1559], dtype=torch.float64, requires_grad=True)

## **Evaluation**

In [20]:
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred = (y_pred > 0.5).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy}')


Accuracy: 0.5153893232345581
